from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class FstabEntry:
    spec: str
    mountpoint: str
    fstype: str
    options: str = "defaults"
    dump: int = 0
    passno: int = 1

    def render(self) -> str:
        return f"{self.spec}\t{self.mountpoint}\t{self.fstype}\t{self.options}\t{self.dump}\t{self.passno}"


def render_fstab(entries: list[FstabEntry]) -> str:
    lines = [
        "# /etc/fstab: static file system information.",
        "# Generated by Blackfong Installer.",
    ]
    lines += [e.render() for e in entries]
    return "\n".join(lines) + "\n"
